### ISSUE TITLE
Cannot access to runtimeConfig in server /api routes

### ISSUE THREAD

**Issue by robinsimonklein** [nuxt-hub/core#304]
**Describe the bug**
runtimeConfig variables are empty in production when deployed via NuxtHub, but ok in local development

**Steps to reproduce**
1. Create a new project in NuxtHub Admin from an existing github repo
2. Configure runtime config in nuxt.config.ts : 
```typescript
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  future: {
    compatibilityVersion: 4,
  },
  devtools: { enabled: true },

  runtimeConfig: {
    cronToken: '',
    public: {
      mapboxToken: '',
    },
  },

  imports: {
    dirs: ['shared/utils']
  },

  modules: ['@nuxt/ui', '@nuxt/eslint', '@nuxthub/core'],

  eslint: {
    // ...
  },

  nitro: {
    imports: {
      dirs: ['shared/utils']
    },
    experimental: {
      tasks: true
    }
  }
});
```
3. Add env variables in Settings → Evironment in NuxtHub Admin (`NUXT_PUBLIC_MAPBOX_TOKEN` & `NUXT_CRON_TOKEN`)
4. Create a `/api` server route to test : 
```typescript
/* /api/debug */
export default defineEventHandler(async () => {
  const runtimeConfig = useRuntimeConfig();
  return { runtimeConfig, process: process.env };
});
```

**Expected behavior**
When I fetch `/api/debug` in development mode on my local setup, I get all the runtimeConfig & process.env variables as expected. 
But in production, all runtimeConfig variables are empty and process.env too : 
```json
{
  "runtimeConfig": {
    "app": {
      "baseURL": "/",
      "buildId": "7fbf412c-ad54-40cc-9236-59a49cd0874e",
      "buildAssetsDir": "/_nuxt/",
      "cdnURL": ""
    },
    "nitro": {
      "envPrefix": "NUXT_",
      "routeRules": {
        "/__nuxt_error": {
          "cache": false
        },
        "/api/_hub/**": {
          "csurf": false
        },
        "/_nuxt/builds/meta/**": {
          "headers": {
            "cache-control": "public, max-age=31536000, immutable"
          }
        },
        "/_nuxt/builds/**": {
          "headers": {
            "cache-control": "public, max-age=1, immutable"
          }
        },
        "/_nuxt/**": {
          "headers": {
            "cache-control": "public, max-age=31536000, immutable"
          }
        }
      }
    },
    "public": {
      "mapboxToken": ""
    },
    "cronToken": "",
    "icon": {
      "serverKnownCssClasses": []
    },
    "hub": {
      "projectUrl": "",
      "projectSecretKey": "",
      "url": "https://admin.hub.nuxt.com",
      "projectKey": "topo-amdo",
      "userToken": "",
      "remote": false,
      "remoteManifest": "",
      "dir": ".data/hub",
      "ai": false,
      "analytics": false,
      "blob": false,
      "browser": false,
      "cache": false,
      "database": false,
      "kv": false,
      "version": "0.7.20",
      "env": "production",
      "openapi": false,
      "bindings": {
        "hyperdrive": {}
      }
    }
  },
  "process": {}
}
```

**Comment by atinux** [comment]
I pushed a fixed yesterday as the new `nodejs_compat_v2` breaks `process.env`.

BTW you won't be able to return `process.env` directly in an API call but you can try to returned a value that should exists (like `process.env.NUXT_HUB_PROJECT_KEY`)

Could you deploy again and check in your Cloudflare project if you have this?

![CleanShot 2024-09-30 at 08 31 07@2x](https://github.com/user-attachments/assets/60b80f38-c27a-4713-be93-763e7ada364f)

**Comment by robinsimonklein** [comment]
Tried to deploy again : I get a value for process.env.NUXT_HUB_PROJECT_KEY but still dont get any value for runtimeConfig vars :/ 

Checked Cloudflare and I have the required Compatibility flags but Compatibility date is on Sep 22, I cannot select Sep 23 🤔 

<img width="1114" alt="Capture d’écran 2024-09-30 à 13 19 29" src="https://github.com/user-attachments/assets/f8ba5ba7-25ad-4a6e-a51f-90028d87bcff">

**Comment by robinsimonklein** [comment]
Maybe should I specifically set runtime vars with `process.env` ?

From
```
  runtimeConfig: {
    cronToken: '',
    public: {
      mapboxToken: '',
    },
  },
  ```
  to 
  ```
  runtimeConfig: {
    cronToken: process.env.NUXT_CRON_TOKEN,
    public: {
      mapboxToken: process.env.NUXT_PUBLIC_MAPBOX_TOKEN,
    },
  },
  ```
  ?

**Comment by atinux** [comment]
> Maybe should I specifically set runtime vars with `process.env` ?
> 
> 
> 
> From
> 
> ```
> 
>   runtimeConfig: {
> 
>     cronToken: '',
> 
>     public: {
> 
>       mapboxToken: '',
> 
>     },
> 
>   },
> 
>   ```
> 
>   to 
> 
>   ```
> 
>   runtimeConfig: {
> 
>     cronToken: process.env.NUXT_CRON_TOKEN,
> 
>     public: {
> 
>       mapboxToken: process.env.NUXT_PUBLIC_MAPBOX_TOKEN,
> 
>     },
> 
>   },
> 
>   ```
> 
>   ?

Yes you should!

**Comment by robinsimonklein** [comment]
Oh that's why ! Thank you 👌

**Comment by sisou** [comment]
So automatic env variable replacing doesn't work for NuxtHub/Cloudflare builds then? Because I had the same problem and found the same solution.

Is that documented anywhere that this automatic replacement (like in dev and with the Node target for example) doesn't work with Cloudflare?

**Comment by atinux** [comment]
I think we can track [https://github.com/unjs/nitro/issues/2054](https://github.com/unjs/nitro/issues/2054)<br><br>As we are implementing the LocalStorage I believe this should soon be fixed!
