### ISSUE TITLE
Can not delete environment variables

### ISSUE THREAD

**Issue by Mehdi-Hp** [nuxt-hub/core#626]
Nuxthub's environment variables are behaving very buggy.
When I delete an item, it doesn't delete it from Cloudflare anymore. Even if I manually delete it from Cloudflare, when I'm trying to add an item with the same name, I get `Duplicated variable keys` error.
I checked the API response from `/variables`, and I'm still getting all the old items that I deleted.

**Comment by farnabaz** [comment]
Hello
This issue should be fixed in yesterday's release. I appreciate if you can try and verify 🙏

**Comment by antonkolo** [comment]
@farnabaz still encountering this issue unfortunately. removed the env variables but can't add them back due to  `Duplicated variable keys` error. Is there a way to fix this?

**Comment by farnabaz** [comment]
@antonkolo What is your project type? is it a CF Worker of it is a Pages project?
